In [1]:
import numpy as np

In [20]:
matrix = [[2,4,3,5,1],[3,1,2,3,4],[1,2,5,2,2],[1,4,2,3,4]]

In [21]:
np.array(matrix)

array([[2, 4, 3, 5, 1],
       [3, 1, 2, 3, 4],
       [1, 2, 5, 2, 2],
       [1, 4, 2, 3, 4]])

In [88]:
def turt(matrix, pr=False):
    m = [0 for i in range(len(matrix[0]))]
    c = np.concatenate([[m], matrix], axis=0)
    m = [[0] for i in range(len(c))]
    c = np.hstack([m, c]) 
    
    
    for i in range(len(matrix)):
        for j in range(len(matrix[0])):
            c[i+1][j+1] = c[i+1][j+1] + max([c[i][j+1],c[i+1][j]])
    
    step = np.zeros((len(matrix),len(matrix[0])))
    l = -1
    k = -1
    step[l][k] = c[l][k]
    for i in range(len(matrix)+len(matrix[0])-2):
        if c[l-1][k]>c[l][k-1]:
            l = l - 1
        else:
            k = k-1
        step[l][k] = c[l][k]
                
    if pr:print(step)
    return(c[-1][-1])

In [89]:
turt(matrix, pr=True)

[[ 2.  6.  9. 14.  0.]
 [ 0.  0.  0. 17. 21.]
 [ 0.  0.  0.  0. 23.]
 [ 0.  0.  0.  0. 27.]]


27